import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionContext from "./components/SessionContext";
import GlobalProvider from "./components/GlobalContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionContext>
          <GlobalProvider>
            <Navbar />
            <Toaster />
            <div className="flex w-full h-[100px] ">
              {/* ini untuk menjaga semua page tidak mepet keatas dan tidak tertutup fixed navbar */}
            </div>
            <div className="
                bg-gradient-to-br from-amber-50 via-amber-50 to-red-100
            ">
              {children}
            </div>
            <Footer />
          </GlobalProvider>
        </SessionContext>
      </body>
    </html>
  );
}
